# This is a workflow to learn to use pandoc in github actions

name: PANDO

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      # Lists files in the repo
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: create file list
        id: files_list
        run: |
          echo "Lorem ipsum" > lorem_1.md  # create two example files
          echo "dolor sit amet" > lorem_2.md
          mkdir output  # create output dir
      - uses: docker://pandoc/latex:3.0
        with:
          entrypoint: /bin/sh
          args: >- 
            -c "find ./ -iname '*.md' -type f -exec sh -c 'pandoc ${0} 
            -o output/${0%.md}.docx' {} \;"
            
      # zips
      - name: List files in the repository
        run: |
          cd output
          zip salida.zip *.docx
          
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
          
      
